### ISSUE TITLE
Breakdown tab throws IllegalArgumentException

### ISSUE THREAD

**Issue by consultantRR** [Netflix/ice#105]
When I click on the Breakdown tab, I get an endless spinning progress indicator beneath the filters pane, and no data ever appears below.

Logs indicate this issue: "The end instant must be greater or equal to the start." See below:

`2014-04-04 18:32:49,866 [http-8080-2] ERROR errors.GrailsExceptionResolver  - IllegalArgumentException occurred when processing request: [POST] /current/dashboard/getData
The end instant must be greater or equal to the start. Stacktrace follows:
java.lang.IllegalArgumentException: The end instant must be greater or equal to the start
	at org.joda.time.base.AbstractInterval.checkInterval(AbstractInterval.java:63)
	at org.joda.time.base.BaseInterval.<init>(BaseInterval.java:94)
	at org.joda.time.Interval.<init>(Interval.java:122)
	at com.netflix.ice.DashboardController.roundInterval(DashboardController.groovy:720)
	at com.netflix.ice.DashboardController.doGetData(DashboardController.groovy:439)
	at com.netflix.ice.DashboardController$_closure11.doCall(DashboardController.groovy:321)
	at java.lang.Thread.run(Thread.java:701)`

Not sure why this is occurring, or how to fix.

**Comment by chezbut** [comment]
Still having this issue, even when setting a future date or today's date in the UI. Note that if the end date is in may 2015 or earlier, there is no issue.
