### ISSUE TITLE
(develop branch) ELB check is broken

### ISSUE THREAD

**Issue by echiu64** [Netflix/ice#177]
```
$ python manage.py find_changes -m elb
Traceback (most recent call last):
  File "manage.py", line 140, in <module>
    manager.run()
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 397, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/__init__.py", line 376, in handle
    return handle(app, *positional_args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_Script-0.6.3-py2.7.egg/flask_script/commands.py", line 145, in handle
    return self.run(*args, **kwargs)
  File "manage.py", line 48, in find_changes
    sm_find_changes(accounts, monitors)
  File "/home/edwin/projs/security_monkey/security_monkey/scheduler.py", line 52, in find_changes
    _find_changes(accounts, monitor, debug)
  File "/home/edwin/projs/security_monkey/security_monkey/scheduler.py", line 69, in _find_changes
    (items, exception_map) = cw.slurp()
  File "/home/edwin/projs/security_monkey/security_monkey/watchers/elb.py", line 119, in slurp
    self._setup_botocore(account)
  File "/home/edwin/projs/security_monkey/security_monkey/watchers/elb.py", line 80, in _setup_botocore
    self.botocore_elb = self.botocore_session.get_service('elb')
AttributeError: 'Session' object has no attribute 'get_service'
```

**Comment by echiu64** [comment]
Oops, wrong project... nevermind
