### ISSUE TITLE
Faias to start with error: ERROR basic.BasicReservationService  - failed to poll reservation prices

### ISSUE THREAD

**Issue by lcykevin** [Netflix/ice#205]
Complete error message:
   Message: You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request ID: e94e0e3e-b8fd-4441-a7c6-f9fc494d8ea1)
    Line | Method
->> 1077 | handleErrorResponse                in com.amazonaws.http.AmazonHttpClient
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    725 | executeOneRequest                  in     ''
|    460 | executeHelper . . . . . . . . . .  in     ''
|    295 | execute                            in     ''
|   9393 | invoke . . . . . . . . . . . . . . in com.amazonaws.services.ec2.AmazonEC2Client
|   7020 | describeReservedInstancesOfferings in     ''
|    152 | pollAPI . . . . . . . . . . . . .  in com.netflix.ice.basic.BasicReservationService
|    106 | init                               in     ''
|     95 | <init> . . . . . . . . . . . . . . in com.netflix.ice.processor.ProcessorConfig
|    186 | doCall                             in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock . in grails.util.Environment
|    320 | executeForEnvironment              in     ''
|    296 | executeForCurrentEnvironment . . . in     ''
|    262 | run                                in java.util.concurrent.FutureTask
|   1145 | runWorker . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor
|    615 | run                                in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run . . . . . . . . . . . . . . .  in java.lang.Thread
| Error java.lang.RuntimeException: failed to poll reservation prices for You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request ID: e94e0e3e-b8fd-4441-a7c6-f9fc494d8ea1)
| Error 	at com.netflix.ice.basic.BasicReservationService.init(BasicReservationService.java:110)
| Error 	at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:95)
| Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
| Error 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| Error 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
| Error 	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
| Error 	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
| Error 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
| Error 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
| Error 	at BootStrap$_closure1.doCall(BootStrap.groovy:186)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error 	at java.lang.reflect.Method.invoke(Method.java:606)
| Error 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
| Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
| Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
| Error 	at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error 	at groovy.lang.Closure.call(Closure.java:423)
| Error 	at groovy.lang.Closure.call(Closure.java:417)
| Error 	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
| Error 	at grails.util.Environment.executeForEnvironment(Environment.java:320)
| Error 	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
| Error 	at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
| Error 	at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
| Error 	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
| Error 	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
| Error 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
| Error 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
| Error 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
| Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
| Error 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
| Error 	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
| Error 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
| Error 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
| Error 	at java.lang.Thread.run(Thread.java:745)
| Error 2016-03-24 11:04:13,265 [localhost-startStop-1] ERROR BootStrap  - Startup failed
Message: failed to poll reservation prices for You are not authorized to perform this operation. (Service: AmazonEC2; Status Code: 403; Error Code: UnauthorizedOperation; Request ID: e94e0e3e-b8fd-4441-a7c6-f9fc494d8ea1)
    Line | Method
->>  110 | init                             in com.netflix.ice.basic.BasicReservationService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
|    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment . . . . .  in     ''
|    296 | executeForCurrentEnvironment     in     ''
|    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                              in java.lang.Thread

Anyone have a workaround for this ?

**Comment by huit-tvachon** [comment]
Your IAM Role doesnt have enough permissions to poll the EC2 API for reservation pricing.  You should look at that, I gave it full EC2 Read Only and I dont see this anymore
