### ISSUE TITLE
Failed to poll reservation prices

### ISSUE THREAD

**Issue by harleythorne** [Netflix/ice#232]
Hi guys,

Though my ice instance is running through the basic.BasicReservationService for a good 10 mins, it eventually fails with the below error (you can see it working in the top 3 lines). 

Currently (for testing only) the AWS user has been given full EC2 access. So I am a little stumped as to what is causing it to fail. Especially since it can do many, many regions successfully - so I don't see how permissions can be the cause.

Any ideas would be greatly appreciated.

Thanks,
Harley

_2016-12-21 12:34:59,514 [localhost-startStop-1] INFO  basic.BasicReservationService  - Setting RI price for us-west-2 HEAVY x1.32xlarge.sqlserverstd 1368552.0 0.0
2016-12-21 12:34:59,514 [localhost-startStop-1] INFO  basic.BasicReservationService  - Setting RI price for us-west-2 HEAVY x1.32xlarge.windows 1514248.0 0.0
2016-12-21 12:34:59,514 [localhost-startStop-1] INFO  basic.BasicReservationService  - Setting RI price for us-west-2 HEAVY x1.32xlarge.windows 1514248.0 0.0_
**| Error 2016-12-21 12:34:59,519 [localhost-startStop-1] ERROR basic.BasicReservationService  - failed to poll reservation prices**
**Message: /mnt/ice_processor/reservation_prices.threeyear.LIGHT (Permission denied)**
    Line | Method
->>  270 | open                             in java.io.FileOutputStream
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    213 | <init>                           in     ''
|    162 | <init> . . . . . . . . . . . . . in     ''
|    191 | pollAPI                          in com.netflix.ice.basic.BasicReservationService
|    106 | init . . . . . . . . . . . . . . in     ''
|     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
|    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment . . . . .  in     ''
|    296 | executeForCurrentEnvironment     in     ''
|    266 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1142 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                              in java.lang.Thread
| Error java.lang.RuntimeException: failed to poll reservation prices for /mnt/ice_processor/reservation_prices.threeyear.LIGHT (Permission denied)
| Error         at com.netflix.ice.basic.BasicReservationService.init(BasicReservationService.java:110)
| Error         at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:95)
| Error         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
| Error         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| Error         at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
| Error         at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
| Error         at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
| Error         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
| Error         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
| Error         at BootStrap$_closure1.doCall(BootStrap.groovy:186)
| Error         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| Error         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error         at java.lang.reflect.Method.invoke(Method.java:497)
| Error         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
| Error         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
| Error         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error         at groovy.lang.Closure.call(Closure.java:423)
| Error         at groovy.lang.Closure.call(Closure.java:417)
| Error         at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
| Error         at grails.util.Environment.executeForEnvironment(Environment.java:320)
| Error         at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
| Error         at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
| Error         at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
| Error         at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
| Error         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
| Error         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
| Error         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
| Error         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
| Error         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
| Error         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
| Error         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
| Error         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
| Error         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
| Error         at java.lang.Thread.run(Thread.java:745)
| Error 2016-12-21 12:34:59,569 [localhost-startStop-1] ERROR BootStrap  - Startup failed
Message: failed to poll reservation prices for /mnt/ice_processor/reservation_prices.threeyear.LIGHT (Permission denied)
    Line | Method
->>  110 | init                             in com.netflix.ice.basic.BasicReservationService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|     95 | <init>                           in com.netflix.ice.processor.ProcessorConfig
|    186 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment . . . . .  in     ''
|    296 | executeForCurrentEnvironment     in     ''
|    266 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1142 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                              in java.lang.Thread

**Comment by harleythorne** [comment]
Oops, easy fix. 

I had to chown -R on /mnt/ice_* 

Sorry!
