### ISSUE TITLE
un-cute AWS s3 error message on startup.

### ISSUE THREAD

**Issue by client9** [Netflix/ice#72]
Not completely sure what is breaking, and this error message isn't helping ;-)

A nice error message saying "hey, we are trying to (read|write) (bucket name)" would greatly improve debugging (assuming this is the problem).

thanks!  Looking forward to getting this working...

ok, back to debugging... thanks!

nickg

| Error AmazonS3Exception: Status Code: 403, AWS Service: Amazon S3, AWS Request ID: FD5A4301E1B43050, AWS Error Code: SignatureDoesNotMatch, AWS Error Message: The request signature we calculated does not match the signature you provided. Check your key and signing method., S3 Extended Request ID: xxx/yyy
| Error     at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:686)
| Error     at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:350)
| Error     at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:202)
| Error     at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3066)
| Error     at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:961)
| Error     at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:847)
| Error     at com.netflix.ice.common.AwsUtils.download(AwsUtils.java:334)
| Error     at com.netflix.ice.common.AwsUtils.download(AwsUtils.java:329)
| Error     at com.netflix.ice.common.AwsUtils.downloadFileIfNotExist(AwsUtils.java:317)
| Error     at com.netflix.ice.basic.BasicReservationService.init(BasicReservationService.java:96)
| Error     at com.netflix.ice.processor.ProcessorConfig.<init>(ProcessorConfig.java:93)
| Error     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
| Error     at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
| Error     at java.lang.reflect.Constructor.newInstance(Constructor.java:532)
| Error     at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:975)
| Error     at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
| Error     at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
| Error     at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57)
| Error     at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182)
| Error     at BootStrap$_closure1.doCall(BootStrap.groovy:186)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
| Error     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error     at java.lang.reflect.Method.invoke(Method.java:616)
| Error     at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1243)
| Error     at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error     at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1082)
| Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:956)
| Error     at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1106)
| Error     at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906)
| Error     at groovy.lang.Closure.call(Closure.java:412)
| Error     at groovy.lang.Closure.call(Closure.java:406)
| Error     at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:308)
| Error     at grails.util.Environment.executeForEnvironment(Environment.java:301)
| Error     at grails.util.Environment.executeForCurrentEnvironment(Environment.java:277)
| Error     at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
| Error     at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:74)
| Error     at org.codehaus.groovy.grails.web.context.GrailsContextLoader.initWebApplicationContext(GrailsContextLoader.java:108)
| Error     at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:111)
| Error     at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4791)
| Error     at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5285)
| Error     at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
| Error     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
| Error     at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
| Error     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
| Error     at java.util.concurrent.FutureTask.run(FutureTask.java:166)
| Error     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
| Error     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
| Error     at java.lang.Thread.run(Thread.java:679)
| Error 2013-11-05 07:17:52,776 [localhost-startStop-1] ERROR BootStrap  - Startup failed
Message: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    Line | Method
->>  686 | handleErrorResponse              in com.amazonaws.http.AmazonHttpClient

---

|    350 | executeHelper                    in     ''
|    202 | execute . . . . . . . . . . . .  in     ''
|   3066 | invoke                           in com.amazonaws.services.s3.AmazonS3Client
|    961 | getObject . . . . . . . . . . .  in     ''
|    847 | getObject                        in     ''
|    334 | download . . . . . . . . . . . . in com.netflix.ice.common.AwsUtils
|    329 | download                         in     ''
|    317 | downloadFileIfNotExist . . . . . in     ''
|     96 | init                             in com.netflix.ice.basic.BasicReservationService
|     93 | <init> . . . . . . . . . . . . . in com.netflix.ice.processor.ProcessorConfig
|    186 | doCall                           in BootStrap$_closure1
|    308 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    301 | executeForEnvironment            in     ''
|    277 | executeForCurrentEnvironment . . in     ''
|    334 | innerRun                         in java.util.concurrent.FutureTask$Sync
|    166 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1146 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    679 | run                              in java.lang.Thread

**Comment by huit-tvachon** [comment]
Is there any better way to try and track down which issue you have?  I currently have this issue and finding which side is difficult with this bug
